
version: 2

models:
    - name: raw_customer
      description: "my first model to read from source"
      columns:
          - name: c_customer_id
            description: "The primary key for this table"
          - name: c_first_name
            description: "Customer First Name"
          - name: c_last_name
            description: "Customer Last Name"
          - name: c_birth_country
            description: "Customer Birthday"