# Inside models/staging/schema.yml
version: 2

models:
  - name: stg_customers
    config: 
      materialized: view
      schema: STAGING
      description: "Cleaned up raw customers data"  
      
  - name: stg_products
    config: 
      materialized: view
      schema: STAGING
      description: "Cleaned up raw customers data"  

  - name: stg_orders
    config: 
      materialized: view
      schema: STAGING
      description: "Cleaned up raw customers data"  

  - name: stg_order_items
    config: 
      materialized: view
      schema: STAGING
      description: "Cleaned up raw customers data"         