version: 2

sources:
      - name: raw
        database: ECOMMERCE_DBT
        schema: RAW
        tables:
          - name: RAW_CUSTOMERS
            description: This table contains customer information

          - name: RAW_PRODUCTS
            description: This table contains customer information

          - name: RAW_ORDERS
            description: This table contains order information

          - name: RAW_ORDER_ITEMS
            description: This table contains order items information

      - name: ops_raw
        database: ECOMMERCE_DBT
        schema: STAGING
        tables:
          - name: ticket_raw
            description: This table contains ticket information



      

