version: 2

sources:
  - name: raw_data
    database: SNOWFLAKE_SAMPLE_DATA        # 👈 Your source Snowflake database
    schema: TPCDS_SF100TCL
    tables:
      - name: CUSTOMER
      - name: CUSTOMER_ADDRESS
      - name: CUSTOMER_DEMOGRAPHICS
  
  - name: raw
    database: TEST_DB        # 👈 Your source Snowflake database
    schema: TEST_SCHEMA
    tables:
      - name: EMPLOYEES 
        columns:
            - name: Name
              description: "Name of the Employees"
              tests: 
                  - not_null
            - name: Gender
              description: "Gender of the Employees"
              tests: 
                  - not_null
  
        config:                         # 👈 Use a config block for properties
          freshness:                    
            warn_after:
              count: 3
              period: hour
            error_after:
              count: 6
              period: hour
          loaded_at_field: CREATE_DATE    
      
               
        



      

